// Copyright (C) 2023 owoDra

#pragma once

#include "NativeGameplayTags.h"


////////////////////////////////////
// UI.Layer

GUIEXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Modal);
GUIEXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Menu);
GUIEXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Game);
GUIEXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_GameMenu);


////////////////////////////////////
// UI.Action

GUIEXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Action_Escape);
GUIEXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Action_Back);
GUIEXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Action_Cancel);
GUIEXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Action_Confirm);
GUIEXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Action_NextTab);
GUIEXT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Action_PreviousTab);

////////////////////////////////////
// UI.Extension.HUDSlot

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Extension_HUDSlot);
